# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('article_date',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article author',
            new_name='article_author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article date',
            new_name='article_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article text',
            new_name='article_text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article title',
            new_name='article_title',
        ),
    ]
